### ISSUE TITLE
Toggle has incorrect style and does not seem to work on later docfx versions

### ISSUE THREAD

**Issue by jasonboukheir** [perlun/darkerfx#5]
First, thanks for making this theme!

I'm using it with my documentation site at https://careboo.github.io/unity-algorand-sdk/4.0. As you can see when visiting it, the toggle looks like the following:

<img width="416" alt="Screenshot 2022-11-25 at 6 58 52 PM" src="https://user-images.githubusercontent.com/5115126/204070028-2a9d6891-b685-41c2-908d-f2242ec2bb73.png">

and clicking the toggle doesn't change the dark/light mode.

The source code of the generated docs can be found in the `gh-pages` branch:
https://github.com/CareBoo/unity-algorand-sdk/tree/gh-pages/4.0

I was thinking that maybe there was some incompatibility with later docfx versions since they like to do that sort of thing ;).

**Comment by perlun** [comment]
> First, thanks for making this theme!

And thanks to you for using it! 🙏 🙂 

This does indeed seem look a bit off in the screenshot you posted. 🤔 The DocFX version I'm using it with myself is 2.59.4 (https://github.com/perlang-org/perlang/pull/346); it does seem to both work correct there as well as look reasonably styled. See it for yourself on https://perlang.org/

Also, when I open your web site, it both looks and works fine; I can switch between dark and light themes without any issues:

![image](https://user-images.githubusercontent.com/630613/204152730-2e0ccddf-406d-4da5-b956-7765b5bb1aa5.png)

This is with Edge 107.0.1418.42 on Windows 10. What browser are you using in the example above? Is it on mobile or desktop? 🤔

**Comment by jasonboukheir** [comment]
Hi, sorry

I switched to using the `darkfx` theme here ^^. Let me try and get a live site ready that has the darkerfx theme again

**Comment by perlun** [comment]
Alright, no problems. :+1: Feel free to use whichever one of these you prefer. I'll close the issue for now but let's just reopen it if/when you have a live site which shows the problem.
